export const CHANGE_SEARCH_FIELD = "CHANGE_SEARCH_FIELD";

export const REQUEST_CAR_PENDING = "REQUEST_CAR_PENDING";
export const REQUEST_CAR_SUCCESS = "REQUEST_CAR_SUCCESS";
export const REQUEST_CAR_FAILED  = "REQUEST_CAR_FAILED";